
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Images\SEAbassConnect.JPG" />
  </ItemGroup>

  <ItemGroup>
    <COMReference Include="SolidEdgeAssembly">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>3e2b3bd4-f0b9-11d1-bdfd-080036b4d502</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
      <Private>False</Private>
    </COMReference>
    <COMReference Include="DesignManager">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>427c71bd-b200-4421-ab49-12da610b369e</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
      <Private>False</Private>
    </COMReference>
    <COMReference Include="SolidEdgeConstants">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>c467a6f5-27ed-11d2-be30-080036b4d502</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
      <Private>False</Private>
    </COMReference>
    <COMReference Include="SolidEdgeDraft">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>3e2b3bdc-f0b9-11d1-bdfd-080036b4d502</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
      <Private>False</Private>
    </COMReference>
    <COMReference Include="SolidEdgeFileProperties">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>aed8fe52-3129-11d1-bc83-0800360e1e02</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
      <Private>False</Private>
    </COMReference>
    <COMReference Include="SolidEdgeFramework">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>8a7efa3a-f000-11d1-bdfc-080036b4d502</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>True</EmbedInteropTypes>
      <Private>False</Private>
    </COMReference>
    <COMReference Include="SolidEdgeFrameworkSupport">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>943ac5c6-f4db-11d1-be00-080036b4d502</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>True</EmbedInteropTypes>
      <Private>False</Private>
    </COMReference>
    <COMReference Include="SEInstallDataLib">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>42e04299-18a0-11d5-bbb2-00c04f79bea5</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
      <Private>False</Private>
    </COMReference>
    <COMReference Include="SolidEdgeGeometry">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>3e2b3be1-f0b9-11d1-bdfd-080036b4d502</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>True</EmbedInteropTypes>
      <Private>False</Private>
    </COMReference>
    <COMReference Include="SolidEdgePart">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>8a7efa42-f000-11d1-bdfc-080036b4d502</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>True</EmbedInteropTypes>
      <Private>False</Private>
    </COMReference>
    <COMReference Include="RevisionManager">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>df778d1a-0aa4-11d1-bc6e-0800360e1e02</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
      <Private>False</Private>
    </COMReference>
    <COMReference Include="SolidEdgeScreenCapture">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>ba1bed1a-e2b2-41f3-a95e-06696290063e</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>True</EmbedInteropTypes>
      <Private>False</Private>
    </COMReference>
    <COMReference Include="StructureEditor">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>a91aa076-8091-48a7-9f9b-b59bdaf78127</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>True</EmbedInteropTypes>
      <Private>False</Private>
    </COMReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Images\SEAbassConnect.JPG">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
